# Generated by Django 4.1.1 on 2022-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0009_alter_karyawanmodels_telepon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawanmodels',
            name='img',
            field=models.ImageField(blank=True, default='static/img/user.png', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='karyawanmodels',
            name='telepon',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
